/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#005a9e",
        "on-surface-variant": "#414750",
        "on-secondary-fixed-variant": "#2d4867",
        "surface": "#f8f9ff",
        "on-tertiary-fixed": "#321300",
        "inverse-surface": "#2e3035",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#001c38",
        "outline": "#727782",
        "tertiary": "#6b3000",
        "surface-container-highest": "#e1e2e8",
        "on-primary-fixed-variant": "#004881",
        "background": "#f8f9ff",
        "secondary-container": "#bed9ff",
        "on-error": "#ffffff",
        "on-background": "#191c20",
        "tertiary-fixed-dim": "#ffb68a",
        "primary": "#004277",
        "on-secondary-container": "#445f7f",
        "surface-container-high": "#e7e8ee",
        "secondary": "#456080",
        "tertiary-container": "#8e4302",
        "on-secondary-fixed": "#001d36",
        "surface-variant": "#e1e2e8",
        "on-tertiary": "#ffffff",
        "surface-tint": "#1260a5",
        "outline-variant": "#c1c7d2",
        "secondary-fixed-dim": "#adc9ed",
        "on-tertiary-fixed-variant": "#743500",
        "error-container": "#ffdad6",
        "inverse-primary": "#a2c9ff",
        "surface-container-low": "#f2f3fa",
        "surface-container": "#ecedf4",
        "tertiary-fixed": "#ffdbc8",
        "secondary-fixed": "#d1e4ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d3e4ff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#a2c9ff",
        "on-surface": "#191c20",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff0f7",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dae0",
        "on-primary-container": "#b1d1ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffc29d"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
